-- MySQL Script generated by MySQL Workbench
-- Thu Mar 31 14:01:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokedex_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pokedex_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokedex_db` DEFAULT CHARACTER SET utf8 ;
USE `pokedex_db` ;

-- -----------------------------------------------------
-- Table `pokedex_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokedex_db`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex_db`.`pokemon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `national_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pokemon_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_pokemon_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `pokedex_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
